<?php

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Api\LanguageController;
use App\Http\Controllers\Api\AboutDistrictController;
use App\Http\Controllers\Api\BannerController;
use App\Http\Controllers\Api\UsefulLinkController;
use App\Http\Controllers\Api\AboutDpcController;
use App\Http\Controllers\Api\PoliticalRepresentativeController;
use App\Http\Controllers\Api\OrganizationalChartController;
use App\Http\Controllers\Api\DpcDocumentController;
use App\Http\Controllers\Api\DspReportController;
use App\Http\Controllers\Api\DspGalleryImageController;
use App\Http\Controllers\Api\KeyResponsibilityController;
use App\Http\Controllers\Api\RoleDutyController;
use App\Http\Controllers\Api\StaffMemberController;
use App\Http\Controllers\Api\RTIPortalController;
use App\Http\Controllers\Api\ReportController;
use App\Http\Controllers\Api\DownloadController;
use App\Http\Controllers\Api\GalleryController;
use App\Http\Controllers\Api\BlogController;
use App\Http\Controllers\Api\TourismController;
use App\Http\Controllers\Api\SchemeController;

Route::prefix('api')->group(function() {
    Route::get('/content/{section}', [LanguageController::class, 'getSectionContent']);
    // Route::get('/district', [DistrictController::class, 'index']);
    // Route::put('/district', [DistrictController::class, 'update'])->middleware('auth:sanctum');
    Route::get('/districts', [AboutDistrictController::class, 'index']);
    Route::get('/banners', [BannerController::class, 'index']);
    Route::get('/useful-links', [UsefulLinkController::class, 'index']);
    Route::get('/AboutDPC', [AboutDpcController::class, 'index']);
    Route::get('/political-representatives', [PoliticalRepresentativeController::class, 'index']);
    Route::get('/organizational-chart', [OrganizationalChartController::class, 'index']);
    Route::get('/dpc-documents', [DpcDocumentController::class, 'index']);
    Route::get('/dsp-reports', [DspReportController::class, 'index']);
    Route::get('/dsp-gallery-images', [DspGalleryImageController::class, 'index']);
    Route::get('/key-responsibilities', [KeyResponsibilityController::class, 'index']);
    Route::get('/role-duties', [RoleDutyController::class, 'index']);
    Route::get('/staff-members', [StaffMemberController::class, 'index']);
    Route::get('/rti-portal', [RTIPortalController::class, 'index']);
    Route::get('/reports', [ReportController::class, 'index']);
    Route::get('/reports/{report}', [ReportController::class, 'show']);
    Route::get('/downloads', [DownloadController::class, 'index']);
    Route::get('/downloads/{download}', [DownloadController::class, 'show']);
    Route::get('/gallery', [GalleryController::class, 'index']);
    Route::get('/blogs', [BlogController::class, 'index']);
    Route::get('/blogs/{slug}', [BlogController::class, 'show']);
    Route::get('/blogs/category/{category}', [BlogController::class, 'byCategory']);
    Route::get('/blogs/tag/{tag}', [BlogController::class, 'byTag']);
    Route::get('/blogs/categories/all', [BlogController::class, 'categories']);
    Route::get('/blogs/tags/all', [BlogController::class, 'tags']);
    Route::get('/tourism/spots', [TourismController::class, 'index']);
    Route::get('/tourism/spots/{slug}', [TourismController::class, 'show']);
    Route::get('/tourism/gallery', [TourismController::class, 'gallery']);
    Route::get('/schemes', [SchemeController::class, 'index']);
    Route::get('/schemes/{slug}', [SchemeController::class, 'show']);
    Route::get('/schemes/category/{categoryId}', [SchemeController::class, 'byCategory']);
    Route::get('/schemes/{schemeSlug}/document/{documentIndex}', [SchemeController::class, 'downloadDocument']);
});